### ISSUE TITLE
[sim] Wrong and Hard-coded Monitor URL 

### ISSUE THREAD

**Issue by gulyx** [LearnPAd/learnpad#303]
@tomjorquera, I just noticed that here:

https://github.com/LearnPAd/learnpad/blob/master/lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/monitoring/activiti/ProbeEventReceiver.java#L71

there is still a wrong reference to the Monitor URL. Currently the Mon is supposed 
to be deployed on the same host of the simulator, nevertheless I would prefer if
this parameter could be defined in a conf file, so that to avoid re-build due its change.

Maybe you can directly refer the property file @acalabro is using here : 

https://github.com/LearnPAd/learnpad/blob/master/lp-simulation-environment/monitoring/scripts/configFiles/environmentFile#L2

Please let me know.
@gulyx

PS : I must go so please consider the links above only after @woshilapin accepted PR #301

**Comment by woshilapin** [comment]
I just merged #301.

**Comment by tomjorquera** [comment]
Fixed by #309
