### ISSUE TITLE
[sim] Null Pointer exception in the example for SLICE D

### ISSUE THREAD

**Issue by gulyx** [LearnPAd/learnpad#321]
@tomjorquera , following your instructions on the wiki page of SLICE D
and debugging the simulator, i understood that the NULL Pointer Exception is actually raised here : 

https://github.com/LearnPAd/learnpad/blob/master/lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java#L354

should come form something wrong here : 

https://github.com/LearnPAd/learnpad/blob/master/lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/processmanager/activiti/ActivitiProcessManager.java#L341

Could you please check?
Let me know.

( FYI : @acalabro , @woshilapin )

**Comment by gulyx** [comment]
Talking with @tomjorquera resulted that the instructions wrote on the wiki were not correct.
@tomjorquera could you please update the wiki page?

However, even with the new "version of the instruction" an additional null pointer exception is raised.
Specifically it concerns the usersMap in eu.learnpad.simulator.uihandler.webserver.UIHandlerWebImpl which results null. See : 
https://github.com/LearnPAd/learnpad/blob/master/lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/uihandler/webserver/UIHandlerWebImpl.java#L148

**Comment by tomjorquera** [comment]
To clarify the issue, the null pointers exceptions came for the fact that the instructions on the wiki were written for the version of the simulator that will be used for the demo. This version comes preloaded with some infos regarding users and process that are not present in the current main version of the simulator.

Until this version is available, I wrote a new section "Alternate testing instructions" that contains instructions to work in the general case. This version should covers all the need to setup the simulator.
