### ISSUE TITLE
[cw] Remove XWiki notion in user ID

### ISSUE THREAD

**Issue by woshilapin** [LearnPAd/learnpad#352]
The XWiki user IDs are of the form `XWiki.bbarnes` but in the end, a user is using only `bbarnes` to login on CW and every other component may want to deal with a more common ID containing only alphanumerics characters.

We have to remove this prefix `XWiki.` in every user ID that is sent from CW and add it to every user ID that is sent to CW. It's mainly about checking the CW controller or bridge.

**Comment by gulyx** [comment]
Indeed.

As first option I suggested to include a private method "converUserID" in 
https://github.com/LearnPAd/learnpad/blob/master/lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java
which has the responsibility to removes the prefix "XWiki.", if any, and which it is always called dealing with usersIDs.

This would impact on [cp] and [cw] so I add @woshilapin, but also the hardcoded models 
used in [sim], and so also @tomjorquera is involved

**Comment by gulyx** [comment]
@tomjorquera @woshilapin please consider the fixes i proposed with PR #411.
Please check if there any other placese where to apply some fix that concern this issue.

Also, applying this patch I realized that the code we were using at the review looks suffering of a bug. In particular, please consider the XwikiController of the CW at [L153-157](https://github.com/gulyx/learnpad/blob/removeXWIKINotionInUserID/lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java#L153-L157) . If u decomment that code, and try to simulate the process, u will notice on xwiki.log the following cast error : http://hastebin.com/urolunoxav.avrasm

Without that code (as it was in the review) everything goes fine. Also note how the parameter `Collection<UserData> potentialUser` is considered in the [SimulatorBridgeImpl](https://github.com/gulyx/learnpad/blob/removeXWIKINotionInUserID/lp-simulation-environment/simulator/src/main/java/eu/learnpad/simulator/api/impl/SimulatorBridgeImpl.java#L217).

**Comment by gulyx** [comment]
@tomjorquera, i just run the debug session u asked me. As u can see from the screenshot i attached, 
the parameter `potentialUsers` results instantiated as `ArrayList<E>` and its value is : 

> [{id=bbarnes, firstName=Barnaby, lastName=Ranalla, bio=null, pictureURL=http://localhost:8080/null, profileURL=http://localhost:8080/xwiki/bin/view/XWiki/bbarnes}, {id=bbarnes, firstName=Barnaby, lastName=Ranalla, bio=null, pictureURL=http://localhost:8080/null, profileURL=http://localhost:8080/xwiki/bin/view/XWiki/bbarnes}]

![sceendebug](https://cloud.githubusercontent.com/assets/8114713/14635639/9cc3d370-0627-11e6-9328-d7ada3288935.png)

**Comment by gulyx** [comment]
message from @tomjorquera  on skype chat : 

> [14:16:04] Tom Jorquera: What I mean is that, looking at your debug session, it seems that the collection does not contains UserData objects
> [14:16:26] Tom Jorquera: But maps of key-values pairs
> [14:17:06] Tom Jorquera: Since you exception happens as the result of a REST call, it seems that the data passed to the REST call is not unmarshalled correctly

**Comment by gulyx** [comment]
from the suggestion of @tomjorquera i understood that : 
 *  https://github.com/LearnPAd/learnpad/blob/master/lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/CWXwikiBridge.java#L400
* https://github.com/LearnPAd/learnpad/blob/master/lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java#L138

have correct values and types.
So maybe the fact that here : 
 * https://github.com/gulyx/learnpad/blob/removeXWIKINotionInUserID/lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiController.java#L148
the parameter `Collection<UserData> potentialUsers` is because the XWIKI Rest layer in not
processing it as `application/json` as stated in the [XwikiCoreFacadeRestResource of the CW](https://github.com/LearnPAd/learnpad/blob/master/lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/cw/XwikiCoreFacadeRestResource.java#L144)

**Comment by woshilapin** [comment]
I'm starting to think that the Jackson annotation of the `UserData` is not sufficient and then REST implementation doesn't know how to deserialize properly, falling back to a default strategy with `LinkedHashMap` (which is indeed a good default strategy for Json).

See also this [link](http://stackoverflow.com/a/30340915)

**Comment by woshilapin** [comment]
Also, I believe Restlet (which is the implementation for REST) is relying more on Jax-B annotations (maybe he's not good at dealing with JSON at all).  But, from [here](https://github.com/FasterXML/jackson-annotations/wiki/Jackson-Annotations#related), I'm tempted to believe that maybe if we annotate `UserData` objects with Jax-B annotations instead of the more specific Jackson annotation, maybe it can help.

**Comment by woshilapin** [comment]
http://www.baeldung.com/jackson-deserialization

**Comment by tomjorquera** [comment]
Could you test with the proposal in PR #413 ? It tries to fixe the problem by encapsulating the collection into a container element to avoid unmarshalling problem.

**Comment by tomjorquera** [comment]
Since @woshilapin tested and merged the PR, can we consider the issue to be resolved?

**Comment by gulyx** [comment]
@tomjorquera, not yet for me. there is an additional fix that I would like to introduce first. having this ISSUE open remind me what I have to do. :-P

**Comment by gulyx** [comment]
@tomjorquera PR #427 should close this issue when/if accepted.

@woshilapin wherever u are, and if u would like, your comments are welcome :D

**Comment by gulyx** [comment]
closed by PR #427
