### ISSUE TITLE
[mt][testbed] Issues in the Generation Process

### ISSUE THREAD

**Issue by gulyx** [LearnPAd/learnpad#359]
@Bitico @giannirosa and @woshilapin I have been notified by Barbara R. that the current instantiation 
of the testbed does not look fully compliant with the models in ADOXX. So maybe there is some leak in the implementation of the MT chains.
Some of this points can be addressed after the Y2 review, but maybe some of them should be
considered also now since they may impact on the demo of some slice.
The details : 

1. in the gateway pages the information about the description of the possible alternatives (expressed on the edges) is lost. I would be nice to report it close to each name of the following task. See an example here : http://testbed.learnpad.eu/xwiki/bin/view/LP_ME_ADOXX_MODELSET_28600/mod.27772/obj.27791/
1. the section "crossing model" of the pages concerning sub-processes is not reporting the link enabling the browsing mode of the sub-process. See an example here : http://testbed.learnpad.eu/xwiki/bin/view/LP_ME_ADOXX_MODELSET_28600/mod.27772/obj.27782/
1. during browing mode some links are missing. See here :

- http://testbed.learnpad.eu/xwiki/bin/view/LP_ME_ADOXX_MODELSET_28600/mod.27772/obj.27833/

- http://testbed.learnpad.eu/xwiki/bin/view/LP_ME_ADOXX_MODELSET_28600/mod.27908/

**Comment by gulyx** [comment]
@Bitico @giannirosa any news about this issue?

as a side note, @woshilapin noticed that the missing links in step 3 are "wrongly" reported
in the "crossing model" section.

**Comment by giannirosa** [comment]
About that, I need to discuss with Jean. We spoke few days ago but he was
very busy for the Y2 review.

I am going to resolve the issue next week as Jean is available to have a
Skype call with me.

Gianni

PS I will contact you when I have finished.

**Comment by woshilapin** [comment]
Meeting taken with @giannirosa on Monday, stay tuned.

**Comment by gulyx** [comment]
@giannirosa @Bitico @woshilapin any news on this issue?

**Comment by woshilapin** [comment]
We had a call with @giannirosa this Monday and he's working on it.

**Comment by giannirosa** [comment]
Gugliemo, I had a call with Jean and I know the problems.

Actually I have a hard deadline and I cannot work on it. I need a few days.

Thanks in advance,
  Gianni

**Comment by gulyx** [comment]
ok please @giannirosa keep me informed ...

**Comment by gulyx** [comment]
@giannirosa @Bitico and all, after the re-deploy of the testbed from @woshilapin, some of the links used in this issues changed. Please refer to the following ones : 

1. in the gateway pages the information about the description of the possible alternatives (expressed on the edges) is lost. I would be nice to report it close to each name of the following task. See an example here : http://testbed.learnpad.eu/xwiki/bin/view/LP_ME_ADOXX_MODELSET_28600/mod.30048/obj.30067/
2. the section "crossing model" of the pages concerning sub-processes is not reporting the link enabling the browsing mode of the sub-process. See an example here : http://testbed.learnpad.eu/xwiki/bin/view/LP_ME_ADOXX_MODELSET_28600/mod.30048/obj.30061/
3. during browsing mode some links are missing or "wrongly" reported in the "crossing model" section. See here :
- how to browse to the task "Manage Service Of Conference"? : http://testbed.learnpad.eu/xwiki/bin/view/LP_ME_ADOXX_MODELSET_28600/mod.30048/obj.30058/
- how to browse to the gateway that bring back to task "Manage Service Of Conference"? : http://testbed.learnpad.eu/xwiki/bin/view/LP_ME_ADOXX_MODELSET_28600/mod.30048/obj.30106/

**Comment by gulyx** [comment]
@giannirosa @Bitico, any news about this issue?

**Comment by Bitico** [comment]
Hi @gulyx, we are just working on that. As soon as possible we will give a feedback.

**Comment by gulyx** [comment]
the 1st point was solved by PR #468

**Comment by gulyx** [comment]
PR #475 solves points 3.1 and 3.2
Point 2 has not solved yet.

**Comment by gulyx** [comment]
PR #483 solves point 2.
