### ISSUE TITLE
[or] Bug in CBR

### ISSUE THREAD

**Issue by gulyx** [LearnPAd/learnpad#383]
@sandro, please take a look at the modification i introduced in https://github.com/LearnPAd/learnpad/pull/382 .

In particular, please consider the test I added. On my builds that test fails (every if and then). Specifically the test uses the 2 dataset from the demo, and it asks for similar cases 3 times : 
1. with dataset 2
1. with dataset 3
1. with dataset 2
Even each request uses different simulationID, i assume that requests 1 and 3 retund the same result, which is (often) not. In particular when the results do not match a similar case named "Simulation Case <simID>" scored 100% is returned.

Could u please check and let me know?
Thanks.

FYI : @woshilapin, @tomjorquera

**Comment by semmeneg** [comment]
@gulyx The 100% "score" resp. similarity occures because a previous case is considerd as new case and therefore part of the case base. This design makes sense when executing cases. But I agree, not for simulation, where we simulate with the same testcases again and again. 
I'll add a filter for this kind of cases.

**Comment by gulyx** [comment]
ok @semmeneg please let me know.

**Comment by gulyx** [comment]
... and of course please (check and) wait the commits in PR https://github.com/LearnPAd/learnpad/pull/382 are merged by @tomjorquera or @woshilapin

**Comment by tomjorquera** [comment]
PR #382 merged (normally I would not merge PRs unrelated to SIM, but since today is a little special I took upon myself to do it to enable you to move forward :smiley:)

**Comment by gulyx** [comment]
ok this should be solved by an upgrade to the CBRService  by @semmeneg .

in order to bind the latest version of the component, please clean the mvn dependencies "ch.fhnw"

FYI : @acalabro
