### ISSUE TITLE
[mon] Hardcoded localhost address in mon RestResource

### ISSUE THREAD

**Issue by tomjorquera** [LearnPAd/learnpad#391]
@acalabro: 

The RestResource class opens connections using a hardcoded HOSTNAME variable set to `localhost`.

It should at least allows this value to be overrided by a configuration file (use the value set in `restUrlString` maybe ?)

(cc-ing @gulyx)

**Comment by gulyx** [comment]
@acalabro any news on this side?
please let us know.

**Comment by acalabro** [comment]
Comment is here:
I'll update it soon

https://github.com/tomjorquera/learnpad/commit/36c33108bb1d0ae226a8ec9fb7add753378eb766#comments

**Comment by gulyx** [comment]
i understand this issue can be considered closed by PR #419
