### ISSUE TITLE
[mv] hard-coded localhost

### ISSUE THREAD

**Issue by gulyx** [LearnPAd/learnpad#403]
@damianofalcioni apparently the MV has strange behaviour when deployed on 
a machine different from the CW. Specifically the CW cannot connect to MV, as if the MV is not deployed yet. 
A justification we had is that possibly this due to some hard-coded "localhost" still located
somewhere.
Could you please check?

FYI : @woshilapin

**Comment by damianofalcioni** [comment]
@gulyx @woshilapin I've updated the pull with also this fix.

**Comment by woshilapin** [comment]
I just saw your modification but that doesn't make it _not-hardcoded_. I guess the best would be to have it configurable in an external file, like you can see in Content Analysis component or Collaborative Workspace component.

**Comment by damianofalcioni** [comment]
@woshilapin in this case is not needed. I only changed the address where the server is listening on. with the previous 127.0.0.1 the server accept connection only from localhost. Now using 0.0.0.0 it can accept connections from any remote host. I guess this one should be the expected common behavior of the server

**Comment by gulyx** [comment]
ok @damianofalcioni, but i assume you tested it on a distributed environment, right?

**Comment by damianofalcioni** [comment]
yes of course, already tested

**Comment by gulyx** [comment]
ok so i can close this issue.

@damianofalcioni @woshilapin
