### ISSUE TITLE
[ca] errors in the UI on some criteria

### ISSUE THREAD

**Issue by gulyx** [LearnPAd/learnpad#447]
@imatesiu, i run the content analysis on the test model we used for Y2R. Everything went fine, concerning both the analysis and the display of the summary report (e.g. `http://localhost:9092/getanalysis.jsf?id=<someid>`). However, asking for the details about both (and only) the criteria "Presentation Clarity" and "Completeness", I got the following error:

http://hastebin.com/titoyuyapo.avrasm

Any suggestion?

**Comment by imatesiu** [comment]
@gulyx ok I investigated the problem and I have the solution.  The solution soon in the next PR.
