### ISSUE TITLE
[cw] show the event name

### ISSUE THREAD

**Issue by gulyx** [LearnPAd/learnpad#478]
- [x] Extend the class LPCode/LinkClass.xml in order to support the new property (i.e. `trigger`) which stores the name of the event triggering the link.
- [x] Show the new property (i.e. `trigger`) in the UI of the LP-CW 

@giannirosa please check if the name of the property is correct

**Comment by giannirosa** [comment]
Yes, I confirm that the new property is *trigger.*

*lco_p5:XWIKI!Property (  name <- 'trigger',    ...)*

**Comment by gulyx** [comment]
PR #480 solves this issue
