### ISSUE TITLE
[mt] Regression in ATL 

### ISSUE THREAD

**Issue by gulyx** [LearnPAd/learnpad#484]
@giannirosa the PR #481 introduces a regression to the platform.
In the properties `LinkClass.trigger` and `LinkClass.denomination` are now always set to empty.
Please take a look.

**Comment by giannirosa** [comment]
I checked the transformation and I confirm that it works. Following an
excerpt of the resulting artifact:

Property Denomination:

> <object wiki="xwiki"
> space="LP_ME_ADOXX_MODELSET_28600//spaces//mod.30048//spaces//obj.30064"
> pageName="WebHome" className="LPCode.LinkClass" number="5">
>     <property value="con.30156" name="id" type="String"/>
>     <property value="LP_ME_ADOXX_MODELSET_28600" name="targetmodelsetid"
> type="String"/>
>     <property value="mod.30048" name="targetmodelid" type="String"/>
>     <property value="obj.30082" name="targetartifactid" type="String"/>
>     <property value="incoming" name="type" type="StaticList"/>
>     <property value="no" name="denomination" type="String"/>
>     <property value="" name="trigger" type="String"/>
>   </object>


<object wiki="xwiki"
> space="LP_ME_ADOXX_MODELSET_28600//spaces//mod.30048//spaces//obj.30109"
> pageName="WebHome" className="LPCode.LinkClass" number="2">
>     <property value="con.30157" name="id" type="String"/>
>     <property value="LP_ME_ADOXX_MODELSET_28600" name="targetmodelsetid"
> type="String"/>
>     <property value="mod.30048" name="targetmodelid" type="String"/>
>     <property value="obj.30082" name="targetartifactid" type="String"/>
>     <property value="incoming" name="type" type="StaticList"/>
>     <property value="yes" name="denomination" type="String"/>
>     <property value="" name="trigger" type="String"/>
>   </object>


Property trigger:

>  <object wiki="xwiki"
> space="LP_ME_ADOXX_MODELSET_28600//spaces//mod.30048//spaces//obj.30079"
> pageName="WebHome" className="LPCode.LinkClass" number="3">
>     <property value="con.30145" name="id" type="String"/>
>     <property value="LP_ME_ADOXX_MODELSET_28600" name="targetmodelsetid"
> type="String"/>
>     <property value="mod.30048" name="targetmodelid" type="String"/>
>     <property value="obj.30058" name="targetartifactid" type="String"/>
>     <property value="incoming" name="type" type="StaticList"/>
>     <property value="" name="denomination" type="String"/>
>     <property value="Intermediate Event (boundary)-83066" name="trigger"
> type="String"/>
>   </object>



Gianni

**Comment by gulyx** [comment]
Please @giannirosa let me know when u have the fix.

**Comment by giannirosa** [comment]
As we discussed today, the regression you mention (#484) arise on the
object mod.30048 ->obj.30067 -> folder number 4, more exactly the property
denomination is not assigned.

In my previous email, I confirmed that the property is properly set.

About your element, I made other check and I notice that the problem is not
the transformation but the source model exported by ADOXX as you can see by
the picture I attached to this mail (test transfo.jpg).

As further test, I setted such property in the source model (property
Denomination on the id obj.30067) and I obtained the correct value on the
target model.

Please check the source model.

Gianni

[image: Inline image 1]

**Comment by gulyx** [comment]
@giannirosa , sorry no image attached.

**Comment by gulyx** [comment]
@giannirosa I debugged and fixed the ATL transformation with PR #486 .

**Comment by giannirosa** [comment]
Thank you
