### ISSUE TITLE
[sim] wrong deploy

### ISSUE THREAD

**Issue by gulyx** [LearnPAd/learnpad#541]
@tomjorquera sorry but it seems that your modification with PR #540 are not affecting the deployment.
specifcally the file simulation.properties seems not considered.
could you please check?

**Comment by gulyx** [comment]
@tomjorquera running a deeper test ...

**Comment by gulyx** [comment]
... confirmed. the conf file result unsed eitehr if options are given to the build script or if not.
Of course i created the proper dir structure inside `deployment`

**Comment by gulyx** [comment]
probably also the `start` script has to be adapted in order to use the `simulator.property` file not included in the jar ... I am guessing!!

**Comment by tomjorquera** [comment]
Yep my mistake. Forgot that when launching from eclipse, the paths are different! Sorry.

PR #543 fixes that

**Comment by gulyx** [comment]
ok this issue can be considered solved ...
